### PR TITLE
Port sensor update rate fix

### PR DESCRIPTION
**Pull request by iche033**
# 🦟 Bug fix

## Summary

cherry-picked commit from #2863 to `gazebo11`

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by peci1** [comment]
Thanks for the forward port. What about the missing mutex lock?

**Comment by iche033** [comment]
> Thanks for the forward port. What about the missing mutex lock?

ah missed the note about mutex. Added. [82851d1](https://github.com/gazebosim/gazebo-classic/pull/3353/commits/82851d1b66e7e72b391682b974d0c3effe636d2b)

**Comment by traversaro** [comment]
@peci1 does the fix looks ready for merge to you? Thanks!

**Review by peci1 — APPROVED** [review]
Yes, LGTM!

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Ok, I will leave some time for other people to comment, and then I will proceed to merge. Feel free to ping me if I forgot to merge.

**Comment by peci1** [comment]
So, is 2 weeks a long enough incubation period? :)

**Comment by traversaro** [comment]
> So, is 2 weeks a long enough incubation period? :)

Even less, thanks for the ping!

**Comment by EmmanuelMess** [comment]
Sorry to comment on an old PR, but I must ask. Was the IMU provided by "GazeboRosImu" tested? Do other IMU plugins (custom made by third parties, like hector's IMU) need retrofiting?

**Comment by traversaro** [comment]
> Sorry to comment on an old PR, but I must ask. Was the IMU provided by "GazeboRosImu" tested? Do other IMU plugins (custom made by third parties, like hector's IMU) need retrofiting?

If you have a doubt on `GazeboRosImu`, I suggest to open a (new) issue in https://github.com/ros-simulation/gazebo_ros_pkgs . For other IMUs, I suggest to open a new issue in this. However, it increases the chances that somebody replies if you provide more context to your questions, for example: are you experiencing problems with `GazeboRosImu`? Why do you think that third parties IMU plugin need to be retrofitted?

**Pull request merged**
