### PR TITLE
Add GZ_PLUGIN_VISIBLE for tracked plugins

### PR DESCRIPTION
**Pull request by blacksoul000**

### CODE REVIEW

**Review by EdheL — APPROVED** [review]
I need these changes too

**Review by chapulina — APPROVED** [review]
LGTM.

CC @peci1

**Comment by peci1** [comment]
I never saw much into the symbol exposure/hiding magic... CI failed, but it seems unrelated and would deserve a re-run.

**Comment by j-rivero** [comment]
@osrf-jenkins run tests please

**Review by j-rivero — APPROVED** [review]

**Pull request merged**
