### PR TITLE
Cherry-pick from 9 to 11

### PR DESCRIPTION
**Pull request by scpeters**
This cherry-picks some recent pull requests (#2914, #2917, #2918) from gazebo9 to gazebo11. Use rebase and merge.

### CODE REVIEW

**Comment by scpeters** [comment]
@osrf-jenkins run tests please

**Comment by iche033** [comment]
changes look fine. The ABI build gave an error `ERROR: some errors occurred when compiling headers`, not sure why. I don't see anything in this PR that would break ABI though

**Comment by scpeters** [comment]
> changes look fine. The ABI build gave an error `ERROR: some errors occurred when compiling headers`, not sure why. I don't see anything in this PR that would break ABI though

that's the 2nd time; I thought the first time was a flaky error; I'll take a closer look

**Comment by scpeters** [comment]
> > changes look fine. The ABI build gave an error `ERROR: some errors occurred when compiling headers`, not sure why. I don't see anything in this PR that would break ABI though
> 
> that's the 2nd time; I thought the first time was a flaky error; I'll take a closer look

~~~
ERROR: problem with 'find' utility (-1): Cannot allocate memory
ERROR: library objects are not found
~~~

**Comment by scpeters** [comment]
it may be a problem with drogon

**Comment by scpeters** [comment]
@osrf-jenkins run tests please

**Comment by scpeters** [comment]
there were some CI failures due to problems with build machines, but the homebrew job looks fine to me; I'll go ahead and merge without an approval since this code has previously been approved on gazebo9

**Pull request merged**
