### PR TITLE
Support for protobuf >= 22 by using find_package(Protobuf CONFIG)

### PR DESCRIPTION
**Pull request by traversaro**
# 🎉 New feature

Fix compatibility with protobuf >= 22, similar to https://github.com/gazebosim/gz-msgs/pull/346 and other PRs linked there.

## Summary

To minimize the risk of regression when protobuf < 22 is used, the protobuf version is obtained via pkg-config. If protobuf >= 22 is detected, then `find_package(Protobuf CONFIG REQUIRED)`  is used and `protobuf::libprotobuf` and `protobuf::libprotobuf` are linked to make sure that the dependency with abseil is correctly handled.

## Test it

See conda-forge CI that now passes. Probably this PR can also be tested on homebrew that recently upgraded protobuf to 23.2, see https://github.com/Homebrew/homebrew-core/pull/132957 .

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [x] Updated documentation (as needed)
- [x] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by traversaro** [comment]
This patch worked fine in https://github.com/conda-forge/gazebo-feedstock/pull/178 .

**Comment by talregev** [comment]
@traversaro, it seem you fix the windows issue. Are you going to merge it?

**Comment by scpeters** [comment]
I wanted to rerun CI now that the citadel bottles of gazebo11 dependencies are fixed, and I noticed a minor whitespace issue, so I pushed https://github.com/gazebosim/gazebo-classic/pull/3331/commits/c4674eee1ad234d4a74bafc1d3ec401b595d3d63 to rerun CI

**Review by scpeters — APPROVED** [review]
CI looks good

**Pull request merged**
