### PR TITLE
Accept relative paths in SDF files

### LINKED ISSUE #2718: Accept relative paths in URIs
The ability to pass relative paths in SDFormat's URIs was added on [this SDF PR](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/pull-requests/558) and implemented on Ignition Gazebo on [this PR](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/pull-requests/433/page/1).

It would be nice if Gazebo 11, which uses SDF9, could also support relative paths, so more SDF files can be shared between Gazebo-classic and Ignition.

### PR DESCRIPTION
**Pull request by chapulina**
Closes #2718 .

The main motivation for this is to allow more models to be reused between Gazebo-classic and Ignition to ease migration. Comments on this issue are relevant: https://github.com/ignitionrobotics/ign-fuel-tools/issues/77#issuecomment-648548920. I'm planning to document all this on a proper tutorial once the implementation is in.

This is a port of [this ign-gazebo PR](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/pull-requests/433/page/1). 

---

## What's working

I locally modified the [Dumpster](https://app.ignitionrobotics.org/OpenRobotics/fuel/models/Dumpster) model to use relative URIs for visual and collision geometries, as well as materials. Then I verified that it's possible to insert it from the left menu and both client and server load all assets correctly.

---

## TODO

- [x] Add tests
- [x] Check that directly calling `~/factory` with `sdf_filename` works
- [x] Check that actor skins and animations work

### CODE REVIEW

**Comment by azeey** [comment]
Just FYI, #2734 changes how models are spawned from `ModelMaker`.

**Comment by ahcorde** [comment]
I added the `testdb` directory to my `GAZEBO_MODEL_PATH` and I'm not able to include the model with the interface. I'm getting a segfault

```bash
[Wrn] [SystemPaths.cc:464] File or path does not exist [""] [meshes/test.dae]
[Err] [Visual.cc:3043] No mesh specified
```

**Comment by ahcorde** [comment]
@chapulina, I added these lines and there is no segfault:

```
  if (_elem->GetParent() == nullptr){
    return;
  }
```

here https://github.com/osrf/gazebo/blob/737037fb3b302a20b64d596f120b350aed84e0c6/gazebo/common/CommonIface.cc#L513

**Review by ahcorde — CHANGES_REQUESTED** [review]
I made some comments

**Comment by chapulina** [comment]
@ahcorde , all your comments have been addressed on e041cca

**Review by ahcorde — APPROVED** [review]
LGTM. Tested locally too

**Comment by chapulina** [comment]
There are way too many failing tests, I'll take a look at them next week.

**Comment by chapulina** [comment]
Ok, so from the 24 test failures on Ubuntu, 17 claim to be the 1st failure, but they're almost all flaky:

* https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/336/testReport/(root)/UNIT_SonarSensor_TEST/test_ran/history/
* https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/336/testReport/(root)/ActorTest/TrajectoryFromSDF/history/
* https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/336/testReport/(root)/SpeedThreadIslandsTest/DualPR2QuickStep/history/
* https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/336/testReport/(root)/SpeedThreadIslandsTest/MultiplePendulumWorldStep/history/
* https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/336/testReport/(root)/SpeedThreadIslandsTest/MultiplePendulumQuickStep/history/
* https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/336/testReport/(root)/PhysicsEngines_Pioneer2dx/StraightLine_1/history/
* https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/336/testReport/(root)/PhysicsEngines_PhysicsLinkTest/AddForce_3/history/
* https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/336/testReport/(root)/PhysicsEngines_PhysicsFrictionTest/FrictionDemo_3/history/
* https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/336/testReport/(root)/INTEGRATION_joint_spawn/test_ran/history/
* https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/336/testReport/(root)/PhysicsEngines_JointForceTorqueTest/GetForceTorqueWithAppliedForceReset_3/history/
* https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/336/testReport/(root)/PhysicsEngines_JointForceTorqueTest/GetForceTorqueWithAppliedForce_3/history/
* https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/336/testReport/(root)/PhysicsEngines_ImuTest/ImuSensorTestWorld_0/history/
* https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/336/testReport/(root)/PhysicsEngines_ContactSensor/ModelRemoval_3/history/
* https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/336/testReport/(root)/EXAMPLE_examples_build/test_ran/history/


This is the only one which seems to be new, but it passes for me locally and I can't think of how it's related:

* https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/336/testReport/(root)/INTEGRATION_speed/test_ran/history/
* https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/345/testReport/(root)/PhysicsEngines_SpeedTest/history/

**Comment by scpeters** [comment]
I think the windows build is failing since this was merged:

~~~
LINK : fatal error LNK1181: cannot open input file 'stdc++fs.lib'
~~~

[Build Status](https://build.osrfoundation.org/job/gazebo-ci-gazebo11-windows7-amd64/29/) https://build.osrfoundation.org/job/gazebo-ci-gazebo11-windows7-amd64/29/

**Pull request merged**
