### PR TITLE
replace deprecated tbb functionality

### LINKED ISSUE #2867: TBB task is deprecated and removed in oneTBB 2021.01
While compiling gazebo with a recent version of tbb, I noticed this warning:
~~~
$PREFIX/include/tbb/task.h:21:139: note: #pragma message: TBB Warning: tbb/task.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.
 #pragma message("TBB Warning: tbb/task.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.")
~~~

Indeed, apparently the tbb task has been deprecated, see https://github.com/oneapi-src/oneTBB/issues/243 for a related discussion. I did not find any info on whether or when the support for tbb task will be actually removed. If the warning is just for new development, then it probably make sense to just leave tbb support in Classic Gazebo as it is.

### PR DESCRIPTION
**Pull request by acxz**
Resolves #2867

### CODE REVIEW

**Comment by traversaro** [comment]
Hi @acxz, thanks a lot for the PR! Just as a curiosity, did you run the test suite after applying this patch?
 
I can't speak for Gazebo mantainers, but I guess to actually merge this I think it would be easier if the proposed change were controlled by pre-processor logic. In this way, the default behaviour (and more importantly, ABI/API) in platforms that to not use TBB v2021.01 will remain the same, while it would still be possible to easily compile Gazebo on rolling relase distributions such as homebrew, conda-forge or in your case I guess arch. : )

As the API/ABI that changed is part of public header, it is probably better to avoid relying on CMake logic to enable it, as it may be tricky to propagate this to downstream projects, as Gazebo does not install CMake imported targets. A better option may be to just have some preprocessor logic that checks the tbb version (from `TBB_VERSION_MAJOR` or similar pre-processor define), as done for example to support Ogre 1.12 (see https://github.com/osrf/gazebo/blob/2e42eb91e7638da54b36dbb8fdd4ae5e3a310d6d/gazebo/rendering/CustomPSSMShadowCameraSetup.cc#L79 for example).

**Comment by Tobias-Fischer** [comment]
We just tried this in conda-forge but it leads to compile errors - any idea how to resolve them @acxz @traversaro? https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=340869&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

```
2021-06-22T22:18:21.9616957Z FAILED: gazebo/CMakeFiles/libgazebo.dir/Server.cc.o 
2021-06-22T22:18:21.9631388Z $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++  -DBOOST_ALL_NO_LIB -DBOOST_DATE_TIME_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_TEST_DYN_LINK -DBOOST_THREAD_DYN_LINK -DBUILDING_DLL -DHAVE_OPENGL -DIGN_PROFILER_ENABLE=0 -DLIBBULLET_VERSION=3.08 -DLIBBULLET_VERSION_GT_282 -DdIDEDOUBLE -Dlibgazebo_EXPORTS -I../test/gtest/include -I../ -I. -I$PREFIX/include/libusb-1.0 -isystem $PREFIX/include/ignition/msgs5 -isystem $PREFIX/include/ignition/math6 -isystem $PREFIX/include/ignition/transport8 -isystem $PREFIX/include/ignition/common3 -isystem $PREFIX/include/ignition/fuel_tools4 -isystem $PREFIX/include/OGRE/RTShaderSystem -isystem $PREFIX/include/OGRE -isystem $PREFIX/include/OGRE/Terrain -isystem $PREFIX/include/OGRE/Paging -isystem $PREFIX/include/OGRE/Overlay -isystem $PREFIX/include/sdformat-9.3 -isystem $PREFIX/include/uuid -isystem $PREFIX/include/sdformat-9.3/sdf/.. -isystem $PREFIX/include/ignition/cmake2 -isystem $PREFIX/include/eigen3 -isystem $PREFIX/include/bullet -isystem $PREFIX/include/simbody -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/gazebo-11.6.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix       -Wall -Wextra -Wno-long-long -Wno-unused-value -Wfloat-equal -Wshadow -Wswitch-default -Wmissing-include-dirs -pedantic -fvisibility=hidden -fvisibility-inlines-hidden   -s -O3 -DNDEBUG -mssse3 -msse3 -mfpmath=sse -msse -msse2  -fPIC   -fPIC -I$PREFIX/include/uuid -MD -MT gazebo/CMakeFiles/libgazebo.dir/Server.cc.o -MF gazebo/CMakeFiles/libgazebo.dir/Server.cc.o.d -o gazebo/CMakeFiles/libgazebo.dir/Server.cc.o -c ../gazebo/Server.cc
2021-06-22T22:18:21.9641684Z In file included from $PREFIX/include/boost/smart_ptr/detail/sp_thread_sleep.hpp:22,
2021-06-22T22:18:21.9647138Z                  from $PREFIX/include/boost/smart_ptr/detail/yield_k.hpp:23,
2021-06-22T22:18:21.9652142Z                  from $PREFIX/include/boost/smart_ptr/detail/spinlock_gcc_atomic.hpp:14,
2021-06-22T22:18:21.9657002Z                  from $PREFIX/include/boost/smart_ptr/detail/spinlock.hpp:42,
2021-06-22T22:18:21.9685487Z                  from $PREFIX/include/boost/smart_ptr/detail/spinlock_pool.hpp:25,
2021-06-22T22:18:21.9686683Z                  from $PREFIX/include/boost/smart_ptr/shared_ptr.hpp:29,
2021-06-22T22:18:21.9687466Z                  from $PREFIX/include/boost/shared_ptr.hpp:17,
2021-06-22T22:18:21.9695849Z                  from $PREFIX/include/boost/program_options/options_description.hpp:16,
2021-06-22T22:18:21.9697194Z                  from $PREFIX/include/boost/program_options.hpp:15,
2021-06-22T22:18:21.9697789Z                  from ../gazebo/Server.cc:31:
2021-06-22T22:18:21.9719398Z $PREFIX/include/boost/bind.hpp:36:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
2021-06-22T22:18:21.9721380Z    36 | BOOST_PRAGMA_MESSAGE(
2021-06-22T22:18:21.9722122Z       | ^~~~~~~~~~~~~~~~~~~~
2021-06-22T22:18:21.9722801Z In file included from ./gazebo/transport/transport.hh:6,
2021-06-22T22:18:21.9723606Z                  from ../gazebo/gazebo_core.hh:21,
2021-06-22T22:18:21.9724306Z                  from ../gazebo/gazebo.hh:20,
2021-06-22T22:18:21.9724972Z                  from ../gazebo/Server.cc:48:
2021-06-22T22:18:21.9726390Z ../gazebo/transport/Node.hh: In member function 'void gazebo::transport::PublishTask::operator()() const':
2021-06-22T22:18:21.9729906Z ../gazebo/transport/Node.hh:59:33: error: no matching function for call to 'boost::shared_ptr<gazebo::transport::Publisher>::reset() const'
2021-06-22T22:18:21.9731253Z    59 |                 this->pub.reset();
2021-06-22T22:18:21.9732020Z       |                                 ^
2021-06-22T22:18:21.9732740Z In file included from $PREFIX/include/boost/shared_ptr.hpp:17,
2021-06-22T22:18:21.9733548Z                  from $PREFIX/include/boost/program_options/options_description.hpp:16,
2021-06-22T22:18:21.9734376Z                  from $PREFIX/include/boost/program_options.hpp:15,
2021-06-22T22:18:21.9735111Z                  from ../gazebo/Server.cc:31:
2021-06-22T22:18:21.9736403Z $PREFIX/include/boost/smart_ptr/shared_ptr.hpp:685:10: note: candidate: 'void boost::shared_ptr<T>::reset() [with T = gazebo::transport::Publisher]' <near match>
2021-06-22T22:18:21.9737402Z   685 |     void reset() BOOST_SP_NOEXCEPT
2021-06-22T22:18:21.9738027Z       |          ^~~~~
2021-06-22T22:18:21.9739738Z $PREFIX/include/boost/smart_ptr/shared_ptr.hpp:685:10: note:   passing 'const PublisherPtr*' {aka 'const boost::shared_ptr<gazebo::transport::Publisher>*'} as 'this' argument discards qualifiers
2021-06-22T22:18:21.9741517Z $PREFIX/include/boost/smart_ptr/shared_ptr.hpp:690:28: note: candidate: 'template<class Y> void boost::shared_ptr<T>::reset(Y*) [with Y = Y; T = gazebo::transport::Publisher]'
2021-06-22T22:18:21.9742612Z   690 |     template<class Y> void reset( Y * p ) // Y must be complete
2021-06-22T22:18:21.9743303Z       |                            ^~~~~
2021-06-22T22:18:21.9744393Z $PREFIX/include/boost/smart_ptr/shared_ptr.hpp:690:28: note:   template argument deduction/substitution failed:
2021-06-22T22:18:21.9745353Z In file included from ./gazebo/transport/transport.hh:6,
2021-06-22T22:18:21.9755300Z                  from ../gazebo/gazebo_core.hh:21,
2021-06-22T22:18:21.9756255Z                  from ../gazebo/gazebo.hh:20,
2021-06-22T22:18:21.9756981Z                  from ../gazebo/Server.cc:48:
2021-06-22T22:18:21.9757770Z ../gazebo/transport/Node.hh:59:33: note:   candidate expects 1 argument, 0 provided
2021-06-22T22:18:21.9758885Z    59 |                 this->pub.reset();
2021-06-22T22:18:21.9759615Z       |                                 ^
2021-06-22T22:18:21.9760365Z In file included from $PREFIX/include/boost/shared_ptr.hpp:17,
2021-06-22T22:18:21.9761158Z                  from $PREFIX/include/boost/program_options/options_description.hpp:16,
2021-06-22T22:18:21.9761974Z                  from $PREFIX/include/boost/program_options.hpp:15,
2021-06-22T22:18:21.9762698Z                  from ../gazebo/Server.cc:31:
2021-06-22T22:18:21.9764139Z $PREFIX/include/boost/smart_ptr/shared_ptr.hpp:696:37: note: candidate: 'template<class Y, class D> void boost::shared_ptr<T>::reset(Y*, D) [with Y = Y; D = D; T = gazebo::transport::Publisher]'
2021-06-22T22:18:21.9765253Z   696 |     template<class Y, class D> void reset( Y * p, D d )
2021-06-22T22:18:21.9765987Z       |                                     ^~~~~
2021-06-22T22:18:21.9766804Z $PREFIX/include/boost/smart_ptr/shared_ptr.hpp:696:37: note:   template argument deduction/substitution failed:
2021-06-22T22:18:21.9767646Z In file included from ./gazebo/transport/transport.hh:6,
2021-06-22T22:18:21.9768358Z                  from ../gazebo/gazebo_core.hh:21,
2021-06-22T22:18:21.9769015Z                  from ../gazebo/gazebo.hh:20,
2021-06-22T22:18:21.9769693Z                  from ../gazebo/Server.cc:48:
2021-06-22T22:18:21.9770448Z ../gazebo/transport/Node.hh:59:33: note:   candidate expects 2 arguments, 0 provided
2021-06-22T22:18:21.9771427Z    59 |                 this->pub.reset();
2021-06-22T22:18:21.9772163Z       |                                 ^
2021-06-22T22:18:21.9772930Z In file included from $PREFIX/include/boost/shared_ptr.hpp:17,
2021-06-22T22:18:21.9773734Z                  from $PREFIX/include/boost/program_options/options_description.hpp:16,
2021-06-22T22:18:21.9774733Z                  from $PREFIX/include/boost/program_options.hpp:15,
2021-06-22T22:18:21.9775458Z                  from ../gazebo/Server.cc:31:
2021-06-22T22:18:21.9777053Z $PREFIX/include/boost/smart_ptr/shared_ptr.hpp:701:46: note: candidate: 'template<class Y, class D, class A> void boost::shared_ptr<T>::reset(Y*, D, A) [with Y = Y; D = D; A = A; T = gazebo::transport::Publisher]'
2021-06-22T22:18:21.9778230Z   701 |     template<class Y, class D, class A> void reset( Y * p, D d, A a )
2021-06-22T22:18:21.9779005Z       |                                              ^~~~~
2021-06-22T22:18:21.9779856Z $PREFIX/include/boost/smart_ptr/shared_ptr.hpp:701:46: note:   template argument deduction/substitution failed:
2021-06-22T22:18:21.9781845Z In file included from ./gazebo/transport/transport.hh:6,
2021-06-22T22:18:21.9782444Z                  from ../gazebo/gazebo_core.hh:21,
2021-06-22T22:18:21.9782999Z                  from ../gazebo/gazebo.hh:20,
2021-06-22T22:18:21.9783531Z                  from ../gazebo/Server.cc:48:
2021-06-22T22:18:21.9784400Z ../gazebo/transport/Node.hh:59:33: note:   candidate expects 3 arguments, 0 provided
2021-06-22T22:18:21.9785548Z    59 |                 this->pub.reset();
2021-06-22T22:18:21.9786125Z       |                                 ^
2021-06-22T22:18:21.9786697Z In file included from $PREFIX/include/boost/shared_ptr.hpp:17,
2021-06-22T22:18:21.9787322Z                  from $PREFIX/include/boost/program_options/options_description.hpp:16,
2021-06-22T22:18:21.9787979Z                  from $PREFIX/include/boost/program_options.hpp:15,
2021-06-22T22:18:21.9788559Z                  from ../gazebo/Server.cc:31:
2021-06-22T22:18:21.9789930Z $PREFIX/include/boost/smart_ptr/shared_ptr.hpp:706:28: note: candidate: 'template<class Y> void boost::shared_ptr<T>::reset(const boost::shared_ptr<Y>&, boost::shared_ptr<T>::element_type*) [with Y = Y; T = gazebo::transport::Publisher]'
2021-06-22T22:18:21.9791457Z   706 |     template<class Y> void reset( shared_ptr<Y> const & r, element_type * p ) BOOST_SP_NOEXCEPT
2021-06-22T22:18:21.9792127Z       |                            ^~~~~
2021-06-22T22:18:21.9792787Z $PREFIX/include/boost/smart_ptr/shared_ptr.hpp:706:28: note:   template argument deduction/substitution failed:
2021-06-22T22:18:21.9793475Z In file included from ./gazebo/transport/transport.hh:6,
2021-06-22T22:18:21.9794196Z                  from ../gazebo/gazebo_core.hh:21,
2021-06-22T22:18:21.9794705Z                  from ../gazebo/gazebo.hh:20,
2021-06-22T22:18:21.9795219Z                  from ../gazebo/Server.cc:48:
2021-06-22T22:18:21.9795826Z ../gazebo/transport/Node.hh:59:33: note:   candidate expects 2 arguments, 0 provided
2021-06-22T22:18:21.9796895Z    59 |                 this->pub.reset();
2021-06-22T22:18:21.9797419Z       |                                 ^
2021-06-22T22:18:21.9797950Z In file included from $PREFIX/include/boost/shared_ptr.hpp:17,
2021-06-22T22:18:21.9798554Z                  from $PREFIX/include/boost/program_options/options_description.hpp:16,
2021-06-22T22:18:21.9799156Z                  from $PREFIX/include/boost/program_options.hpp:15,
2021-06-22T22:18:21.9799704Z                  from ../gazebo/Server.cc:31:
2021-06-22T22:18:21.9801318Z $PREFIX/include/boost/smart_ptr/shared_ptr.hpp:713:28: note: candidate: 'template<class Y> void boost::shared_ptr<T>::reset(boost::shared_ptr<Y>&&, boost::shared_ptr<T>::element_type*) [with Y = Y; T = gazebo::transport::Publisher]'
2021-06-22T22:18:21.9802431Z   713 |     template<class Y> void reset( shared_ptr<Y> && r, element_type * p ) BOOST_SP_NOEXCEPT
2021-06-22T22:18:21.9803059Z       |                            ^~~~~
2021-06-22T22:18:21.9803699Z $PREFIX/include/boost/smart_ptr/shared_ptr.hpp:713:28: note:   template argument deduction/substitution failed:
2021-06-22T22:18:21.9804391Z In file included from ./gazebo/transport/transport.hh:6,
2021-06-22T22:18:21.9805161Z                  from ../gazebo/gazebo_core.hh:21,
2021-06-22T22:18:21.9805667Z                  from ../gazebo/gazebo.hh:20,
2021-06-22T22:18:21.9806339Z                  from ../gazebo/Server.cc:48:
2021-06-22T22:18:21.9806925Z ../gazebo/transport/Node.hh:59:33: note:   candidate expects 2 arguments, 0 provided
2021-06-22T22:18:21.9807948Z    59 |                 this->pub.reset();
2021-06-22T22:18:21.9808500Z       |                                 ^
2021-06-22T22:18:32.4192715Z [329/1194] Building CXX object gazebo/CMakeFiles/libgazebo.dir/Master.cc.o
2021-06-22T22:18:32.4198152Z In file included from $PREFIX/include/boost/bind.hpp:30,
2021-06-22T22:18:32.4201871Z                  from ../gazebo/Master.cc:22:
2021-06-22T22:18:32.4205901Z $PREFIX/include/boost/bind.hpp:36:1: note: #pragma message: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
2021-06-22T22:18:32.4209282Z    36 | BOOST_PRAGMA_MESSAGE(
2021-06-22T22:18:32.4212328Z       | ^~~~~~~~~~~~~~~~~~~~
```

**Comment by scpeters** [comment]
thanks for your attempt to make progress on #2867, but this doesn't compile, so I'm going to close it for now. I encourage you to continue discussion of how to resolve this in #2867

**Comment by Tobias-Fischer** [comment]
Hi @scpeters @acxz - to clarify, I am not sure whether the above compile issues are due to conda-forge or happen in general. It could well be that there is something conda-forge specific going wrong.

**Comment by scpeters** [comment]
> Hi @scpeters @acxz - to clarify, I am not sure whether the above compile issues are due to conda-forge or happen in general. It could well be that there is something conda-forge specific going wrong.

I confirmed the compilation errors by looking at the output of our homebrew CI job:

* https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/2447/console

**Pull request closed without merging**
