### PR TITLE
Test ABI compatibility of physics-sensor lockstep

### PR DESCRIPTION
**Pull request by mabelzhang**
Created this to trigger ABI checker on Jenkins correctly (hopefully).

### CODE REVIEW

**Comment by iche033** [comment]
ABI checker build is green! I think this PR is ready fro review :)

**Comment by iche033** [comment]
small update to make lockstepping work for wide-angle cameras. b35191322d97e7476fc8658dc2bda62da3645c27

**Comment by mabelzhang** [comment]
ubuntu gpu-none has these test failures that are not in the buildfarm CI. They all seem related to timing:

PhysicsEngines/ContactSensor.ModelRemoval/0
PhysicsEngines/ContactSensor.ModelRemoval/3
On the same line:
```
/var/lib/jenkins/workspace/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/gazebo/test/integration/contact_sensor.cc:164
Expected: (j) < (5), actual: 5 vs 5
```
It's waiting for topic cleanup, and they aren't being cleaned up.

PhysicsEngines/ImuTest.ImuSensorTestWorld/0
```
/var/lib/jenkins/workspace/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/gazebo/test/integration/imu.cc:303
The difference between imuMag and gMag is 9.5427824541971518e-05, which exceeds 8e-5, where
imuMag evaluates to 9.8100954278245425,
gMag evaluates to 9.8100000000000005, and
8e-5 evaluates to 8.0000000000000007e-05.
```
This is inside an else-if-condition `(world->SimTime().Double() >= 1.85)`. I think it's expecting different values depending on how much time has passed.

SpeedThreadIslandsTest.MultiplePendulumQuickStep
SpeedThreadIslandsTest.MultiplePendulumWorldStep
SpeedThreadIslandsTest.DualPR2QuickStep
On the same line:
```
/var/lib/jenkins/workspace/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/gazebo/test/integration/speed_thread_islands.cc:150
Expected: (threadMinTime) < (baseMinTime), actual: 2 317337200 vs 2 89550522
```
It's comparing the time between threading and no threading.

I could not reproduce any of these locally... I thought we had made the timing issue better with `--lockstep`...

**Comment by mabelzhang** [comment]
Ooh I'm seeing all these failures in #2788 as well: https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-none/240/

PhysicsEngines/ContactSensor.ModelRemoval/2
PhysicsEngines/ContactSensor.ModelRemoval/3
PhysicsEngines/ImuTest.ImuSensorTestWorld/0
SpeedThreadIslandsTest.MultiplePendulumQuickStep
SpeedThreadIslandsTest.MultiplePendulumWorldStep
SpeedThreadIslandsTest.DualPR2QuickStep

This is the same set as above. So they're just flaky. I think this PR is good to go then.

**Comment by iche033** [comment]
lockstep is working with manual testing. ABI build is fine. Approving!

**Review by iche033 — APPROVED** [review]

**Comment by iche033** [comment]
hmm we should probably give this PR a better title before merging.

**Comment by mabelzhang** [comment]
xD Thanks for changing the title. Merging!

**Pull request merged**
