### PR TITLE
Add Gazebo classic end-of-life notice

### PR DESCRIPTION
**Pull request by azeey**
Gazebo Classic is [reaching EOL in 2025](https://community.gazebosim.org/t/gazebo-classic-end-of-life/2563). This adds a notice to our users letting them know that and encouraging them to migrate to the new Gazebo

### Command line
image

### GUI Menu bar
image

### GUI About Gazebo dialog
image

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Review by traversaro — APPROVED** [review]

**Comment by azeey** [comment]
I've added the EOL notice to the GUI as well. @ahcorde @traversaro , can you take another look?

**Review by traversaro — APPROVED** [review]

**Review by iche033 — APPROVED** [review]

**Comment by j-rivero** [comment]
I've removed Bionic and Debian Buster (EOL) from the release info and bump Focal in https://github.com/gazebo-release/gazebo11-release/pull/14

**Comment by peci1** [comment]
What about adding an env variable to turn off this warning? We'd like to finish this summer semester with G Classic and do the upgrade afterwards. I'm really "looking forward" for all the students being even more confused than they already are...

**Comment by scpeters** [comment]
> What about adding an env variable to turn off this warning? We'd like to finish this summer semester with G Classic and do the upgrade afterwards. I'm really "looking forward" for all the students being even more confused than they already are...

something like `GAZEBO_SUPPRESS_EOL_WARNING`?

**Comment by peci1** [comment]
Yes, that would be great.

**Comment by j-rivero** [comment]
I was going to release the thing but I think that we can wait until today's Gazebo meeting (happening in 7 hours). It would be great if we a have a pull request implementing the `GAZEBO_SUPPRESS_EOL_WARNING` idea.

**Pull request merged**
