### PR TITLE
Compile test plugins as MODULE instead of STATIC

### LINKED ISSUE #2883: PluginTest failing since plugins became static libraries
These tests started failing recently:

* `PluginTest.ModelExceptionConstructor`
* `PluginTest.ModelExceptionInit`
* `PluginTest.ModelExceptionLoad`

I can reproduce the failures locally. The problem is that the plugins can't be loaded anymore. Here's the test log:

```
[Err] [Plugin.hh:178] Failed to load plugin libExceptionModelPluginConstructor.so: libExceptionModelPluginConstructor.so: cannot open shared
 object file: No such file or directory                                                                                                     
...
/home/chapulina/gazebo11_ws/src/gazebo/test/integration/plugin.cc:58: Failure                                  
Value of: loggedString.find( "Exception occured in the constructor of plugin with name") != std::string::npos
  Actual: false                                                                         
Expected: true
```

Changing the libraries to `SHARED` here fixes the tests for me:

https://github.com/osrf/gazebo/blob/5ecd18aead9cf70574486979b161ad5c12a5faa2/test/plugins/CMakeLists.txt#L34

This was changed to `STATIC` on #2753 and #2754.

@j-rivero , do you think we can revert that one change? Or maybe fix the test some other way? Right now the plugins have `.a` extensions and the test is expecting `.so`.

### PR DESCRIPTION
**Pull request by j-rivero**
Revert part of #2753 which change the compilation of plugins to STATIC.

Should fix #2883 in the gazebo11 branch. Needs to be tested on ARM.

### CODE REVIEW

**Comment by scpeters** [comment]
we still need to test with ARM, but just looking at our other supported platforms, I believe this has fixed the tests on Ubuntu amd64, but the macOS tests are still broken. apparently `MODULE` libraries have a `.so` suffix on macOS (while shared libraries end with `.dylib`, see #800 and this [stackover answer](https://stackoverflow.com/a/2339910)), so I think we'll need to update the logic in [Plugin.hh](https://github.com/osrf/gazebo/blob/6fd426b3949c4ca73fa126cde68f5cc4a59522eb/gazebo/common/Plugin.hh#L126-L134) in order to load `.so` files as plugins on macOS

~~~
[ 53%] Linking CXX shared module libExceptionModelPluginConstructor.so
...
[ 53%] Linking CXX shared module libExceptionModelPluginInit.so
~~~

we don't need to block this PR on macOS; if it fixes Ubuntu amd64 and ARM, we can add some comments to #800 about this and follow up later

**Comment by j-rivero** [comment]
> Needs to be tested on ARM.

Let's try [Build Status](https://build.osrfoundation.org/job/_test_gazebo-ci-pr_any-ubuntu_auto-arm64-gpu-nvidia/)

> apparently `MODULE` libraries have a `.so` suffix on macOS (while shared libraries end with `.dylib`, see #800 and this [stackover answer](https://stackoverflow.com/a/2339910)), so I think we'll need to update the logic in [Plugin.hh](https://github.com/osrf/gazebo/blob/6fd426b3949c4ca73fa126cde68f5cc4a59522eb/gazebo/common/Plugin.hh#L126-L134) in order to load `.so` files as plugins on macOS

Interesting. I agree on following on #800.

**Comment by scpeters** [comment]
@j-rivero I just merged with `gazebo11`, so this should be up to date now. Do you think we can try another ARM test build of this branch?

**Comment by scpeters** [comment]
arm test build:

* [Build Status](https://build.osrfoundation.org/job/_test_gazebo-ci-pr_any-ubuntu_auto-arm64-gpu-nvidia/3/) https://build.osrfoundation.org/job/_test_gazebo-ci-pr_any-ubuntu_auto-arm64-gpu-nvidia/3/

**Comment by scpeters** [comment]
> arm test build:
> 
> * [Build Status](https://build.osrfoundation.org/job/_test_gazebo-ci-pr_any-ubuntu_auto-arm64-gpu-nvidia/3/) https://build.osrfoundation.org/job/_test_gazebo-ci-pr_any-ubuntu_auto-arm64-gpu-nvidia/3/

I started another job but it didn't finish

[Build Status](https://build.osrfoundation.org/job/_test_gazebo-ci-pr_any-ubuntu_auto-arm64-gpu-nvidia/4/) https://build.osrfoundation.org/job/_test_gazebo-ci-pr_any-ubuntu_auto-arm64-gpu-nvidia/4/

**Comment by scpeters** [comment]
it's looking better; the arm build succeeded, though there are more test failures than normal and the console output suggests a runtime problem

~~~
395: Unsupported setsockopt level=0 optname=32
395: Error setting socket option (IP_MULTICAST_IF).
395: Unsupported setsockopt level=0 optname=32
395: Error setting socket option (IP_MULTICAST_IF).
395: Did you set the environment variable IGN_IP with a correct IP address? 
395:   [172.17.0.2] seems an invalid local IP address.
395:   Using 127.0.0.1 as hostname.
395: terminate called after throwing an instance of 'std::out_of_range'
395:   what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
395: qemu: uncaught target signal 6 (Aborted) - core dumped
~~~

[Build Status](https://build.osrfoundation.org/job/_test_gazebo-ci-pr_any-ubuntu_auto-arm64-gpu-nvidia/7/) https://build.osrfoundation.org/job/_test_gazebo-ci-pr_any-ubuntu_auto-arm64-gpu-nvidia/7/

the windows build is failing though

~~~
Scanning dependencies of target gtest_main
Error: dependent 'test\gtest.lib' does not exist.
~~~

[Build Status](https://build.osrfoundation.org/job/gazebo-ci-pr_any-windows7-amd64/3203/) https://build.osrfoundation.org/job/gazebo-ci-pr_any-windows7-amd64/3203/

**Review by scpeters — APPROVED** [review]
thanks for all the iteration and fixing the changelog!

**Pull request merged**
