### PR TITLE
Merge 9.14.0 -> 10

### PR DESCRIPTION
**Pull request by scpeters**
We haven't merged forward from gazebo9 to 10 or 11 in quite some time. I'll start by merging forward from 9.14.0 to gazebo10, since a significant change to gazebo transport (#2812) was merged just before that tag. The changes to transport conflict with changes made in gazebo 10.0.0 ([bitbucket pull request 2922](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/pull-requests/2922/page/1)). Given that there were [noted issues with exceptions](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/pull-requests/2922/page/1#comment-61693019) during the review of the pull request to gazebo10; I've reverted most of the changes from [bitbucket pull request 2922](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/pull-requests/2922/page/1) in favor of #2812 while resolving merge conflicts. We should look closely at CI and see if there is anything worth keeping from the reverted code.

cc @parrotepicuser @iche033 @chapulina

### CODE REVIEW

**Comment by scpeters** [comment]
I cherry-picked #2865 to fix the macOS build

**Comment by scpeters** [comment]
looks like I also removed the logic from bitbucket PR 2657 (5ca6ba343bac12b448c50911cae36916e7be2c34), which should be restored

I noticed a local failure of `INTEGRATION_transport_msg_count`

**Comment by chapulina** [comment]
Gazebo 10 is already EOL, so I think this PR may not be worth the risk of introducing a regression on a final minor release.

**Comment by scpeters** [comment]
> Gazebo 10 is already EOL, so I think this PR may not be worth the risk of introducing a regression on a final minor release.

ok, I'll try merging directly to 11 instead

**Pull request closed without merging**
