### PR TITLE
Distortion initialization fix with background color

### LINKED ISSUE #2527: Last camera's distortion affects previous cameras' distortions
**Original report ([archived issue](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/issues/2527)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
See the following world for example, where the first camera appears to have barrel distortion even though it was supposed to be pincushion. Swapping the order of models in the world makes both cameras be pincushion.

~~~
<?xml version="1.0" ?>
<sdf version="1.6">
  <world name="default">

    <include>
      <uri>model://sun</uri>
    </include>

    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>100 100</size>
            </plane>
          </geometry>
          <surface>
            <friction>
              <ode>
                <mu>100</mu>
                <mu2>50</mu2>
              </ode>
            </friction>
              <bounce>
                <restitution_coefficient>1.0</restitution_coefficient>
                <threshold>0</threshold>
              </bounce>
              <contact>
                <ode>
                  <max_vel>10000</max_vel>
                  <min_depth>0.001</min_depth>
                </ode>
              </contact>
          </surface>
        </collision>
        <visual name="visual">
          <cast_shadows>false</cast_shadows>
          <geometry>
            <plane>
              <normal>0 0 1</normal>
              <size>100 100</size>
            </plane>
          </geometry>
          <material>
            <script>
              <uri>file://media/materials/scripts/gazebo.material</uri>
              <name>Gazebo/Grey</name>
            </script>
          </material>
        </visual>
      </link>
    </model>

    <model name="ball">
      <allow_auto_disable>false</allow_auto_disable>
      <pose>-1 0 1 0 0 0</pose>
      <static>false</static>
      <link name="link">
        <inertial>
          <mass>0.026</mass>
          <!-- inertia based on solid sphere 2/5 mr^2 -->
          <inertia>
            <ixx>1.664e-5</ixx>
            <iyy>1.664e-5</iyy>
            <izz>1.664e-5</izz>
            <ixy>0</ixy>
            <ixz>0</ixz>
            <iyz>0</iyz>
          </inertia>
        </inertial>
        <collision name="collision">
          <geometry>
            <sphere>
              <radius>0.04</radius>
            </sphere>
          </geometry>
          <surface>
            <bounce>
              <restitution_coefficient>1.0</restitution_coefficient>
              <threshold>0</threshold>
            </bounce>
            <contact>
              <ode>
                <max_vel>10000</max_vel>
                <min_depth>0.001</min_depth>
              </ode>
            </contact>
          </surface>
        </collision>
        <visual name="visual">
          <geometry>
            <sphere>
              <radius>0.04</radius>
            </sphere>
          </geometry>
        </visual>
      </link>
    </model>

    <model name="camera_pincushion">
      <pose>0 0 0.5 0 0 3.14</pose>
      <static>true</static>
      <link name="pincushion">
        <sensor type="camera" name="camera_pincushion">
          <update_rate>60</update_rate>
          <visualize>true</visualize>
          <camera name="head">
            <horizontal_fov>0.927295218</horizontal_fov>
            <image>
              <width>640</width>
              <height>480</height>
              <format>R8G8B8</format>
            </image>
            <clip>
              <near>0.02</near>
              <far>300</far>
            </clip>
            <distortion>
              <k1>0.1</k1>
              <k2>0.1</k2>
              <p1>0</p1>
              <p2>0</p2>
              <k3>0.1</k3>
              <center>0.5 0.5</center>
            </distortion>
          </camera>
        </sensor>
      </link>
    </model>

    <model name="camera_barrel">
      <pose>0 0 0.5 0 0 3.14</pose>
      <static>true</static>
      <link name="barrel">
        <sensor type="camera" name="camera_barrel">
          <update_rate>60</update_rate>
          <visualize>true</visualize>
          <camera name="head">
            <horizontal_fov>0.927295218</horizontal_fov>
            <image>
              <width>640</width>
              <height>480</height>
              <format>R8G8B8</format>
            </image>
            <clip>
              <near>0.02</near>
              <far>300</far>
            </clip>
            <distortion>
              <k1>-0.1</k1>
              <k2>-0.1</k2>
              <p1>0</p1>
              <p2>0</p2>
              <k3>-0.1</k3>
              <center>0.5 0.5</center>
            </distortion>
          </camera>
        </sensor>
      </link>
    </model>

    <include>
      <pose>-1.5 0 1 0 1.57 0</pose>
      <uri>model://checkerboard_plane</uri>
    </include>
  </world>
</sdf>
~~~

### PR DESCRIPTION
**Pull request by WilliamLewww**
Closes #2527 - Last camera's distortion affects previous cameras' distortions

When setting the background color to a scene, the distortion parameters continue to leak. From #3033 we can infer that setting the scene's background color is effecting the distortion compositor which is causing the improper order for compositor initialization.

To fix the issue, we reinitialize the distortion after setting the scene's color to ensure the distortion compositor is properly set for each camera.

### CODE REVIEW

**Comment by scpeters** [comment]
this has merge conflicts that need to be resolved

**Comment by scpeters** [comment]
I tightened some test expectations in 0fe817c

**Comment by scpeters** [comment]
for some reason, there is a regressions in `CameraSensor.CheckNewAndLegacyDistortionModes`:

* https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-nvidia/760/testReport/junit/(root)/CameraSensor/CheckNewAndLegacyDistortionModes/
* https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/2520/testReport/junit/(root)/CameraSensor/CheckNewAndLegacyDistortionModes/

I added a `getchar()` statement to the end of the test so I could open a gzclient instance and view the images generated in the test. It appears that with this pull request, the distortion of the `pincushion_legacy` camera images has changed (all other images appeared unchanged).

Since the `pincushion_legacy` camera is the first one spawned in the test, I tried changing the order in which they are spawned, and I noticed that the distortion of the first spawned camera seems to be different than if it was spawned later. I'm still debugging this, but I think it's something we need to fix

**Comment by scpeters** [comment]
> for some reason, there is a regressions in `CameraSensor.CheckNewAndLegacyDistortionModes`:
> 
> * https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-nvidia/760/testReport/junit/(root)/CameraSensor/CheckNewAndLegacyDistortionModes/
> * https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/2520/testReport/junit/(root)/CameraSensor/CheckNewAndLegacyDistortionModes/
> 
> I added a `getchar()` statement to the end of the test so I could open a gzclient instance and view the images generated in the test. It appears that with this pull request, the distortion of the `pincushion_legacy` camera images has changed (all other images appeared unchanged).
> 
> Since the `pincushion_legacy` camera is the first one spawned in the test, I tried changing the order in which they are spawned, and I noticed that the distortion of the first spawned camera seems to be different than if it was spawned later. I'm still debugging this, but I think it's something we need to fix

I've added a test to detect the problems with the first distorted images in edd5d43

**Comment by WilliamLewww** [comment]
The tests are working now! Turns out that the distortion effect was magnified because refreshing the compositor just adds another compositor on top of the existing one. To fix the issue, I remove the compositor right before adding the new one.

**Comment by scpeters** [comment]
> The tests are working now! Turns out that the distortion effect was magnified because refreshing the compositor just adds another compositor on top of the existing one. To fix the issue, I remove the compositor right before adding the new one.

great work!

**Comment by scpeters** [comment]
I noticed you relaxed some test tolerances in ff32b82 by necessity; I've tightened them back a bit in 4d284d7

I also squeezed in some fixes for clang warnings in c6d3bb9 and e47c87e and merged with gazebo11 to fix the ABI checker build

**Review by scpeters — APPROVED** [review]

**Pull request merged**
