### PR TITLE
[Forward Port Gazebo 11] Publish performance metrics (#2819)

### PR DESCRIPTION
**Pull request by ahcorde**
Forward Port to Gazebo 11 - Publish performance metrics

Signed-off-by: ahcorde <ahcorde@gmail.com>
Co-authored-by: Ian Chen <ichen@osrfoundation.org>

### CODE REVIEW

**Comment by iche033** [comment]
@osrf-jenkins  run tests please

**Comment by iche033** [comment]
works for me. 

The last couple of jenkins windows builds failed due to an issue with the machine itself. Triggering another one..

**Comment by ahcorde** [comment]
@osrf-jenkins run tests please

**Comment by iche033** [comment]
windows build finished. I think there is an issue with gazebo's window build in general. The jenkins report shows 2 tests failures but the console output shows: `1% tests passed, 389 tests failed out of 392` :( Looks like it's also happening in previous builds so not introduced by this PR.

**Review by iche033 — APPROVED** [review]

**Review by chapulina — APPROVED** [review]
I haven't ran it, but it looks like the one on Gazebo 9 and CI is ok.

**Pull request merged**
