### PR TITLE
Fix typo in the check for whether the TBB target exists in gazebo-config.cmake.in

### PR DESCRIPTION
**Pull request by kartikmohta**

### CODE REVIEW

**Comment by j-rivero** [comment]
Thanks for the PR Kartik! Could it be the case that different package systems are offering the tbb component with different names, sometimes in uppercase, sometimes in lowercase?  Do you have a pointer at hand to the upstream code that generates the CMake component?

**Comment by traversaro** [comment]
Thanks @kartikmohta , indeed I think this was an error introduced in https://github.com/osrf/gazebo/pull/3174 .

**Comment by scpeters** [comment]
> Thanks for the PR Kartik! Could it be the case that different package systems are offering the tbb component with different names, sometimes in uppercase, sometimes in lowercase? Do you have a pointer at hand to the upstream code that generates the CMake component?

it does look like a fix of a typo to me, since it now matches the target name on line 230

**Comment by scpeters** [comment]
thanks so much for the fix!

**Review by scpeters — APPROVED** [review]

**Review by j-rivero — APPROVED** [review]

**Review by scpeters — APPROVED** [review]

**Pull request merged**
