### PR TITLE
[Bug Fix] Fix windows compilation

### PR DESCRIPTION
**Pull request by talregev**
Fix windows compilation.

### CODE REVIEW

**Comment by scpeters** [comment]
it looks like the windows build still has some issues

**Comment by talregev** [comment]
> it looks like the windows build still has some issues

Yes. Gazebo using c++17 syntax and the 3rdparty is compile with c++11. This is abi issue.

**Comment by traversaro** [comment]
> > it looks like the windows build still has some issues
> 
> Yes. Gazebo using c++17 syntax and the 3rdparty is compile with c++11. This is abi issue.

Are you sure? The problem seems that (just on Windows) protobuf is now updated to version 23, that has several changes including the public dependency on abseil (see https://github.com/gazebosim/gz-msgs/pull/346 for similar issue). I think changing https://github.com/gazebosim/gazebo-classic/blob/fbb3d12273b02a382085ebf1f1ba72c4da315112/cmake/gazebo-config.cmake.in#LL169C1-L171C56 to:
~~~
find_package(Protobuf CONFIG)
if(NOT Protobuf_FOUND)
  find_package(Protobuf REQUIRED)
endif()
if(Protobuf_VERSION VERSION_GREATER_EQUAL 4.0.0)
  list(APPEND @PKG_NAME@_LIBRARIES protobuf::libprotobuf protobuf::libprotoc)
else()
  list(APPEND @PKG_NAME@_INCLUDE_DIRS ${PROTOBUF_INCLUDE_DIRS})
  list(APPEND @PKG_NAME@_LIBRARIES ${PROTOBUF_LIBRARIES})
endif()
~~~

may work and reduce the risk of regression for older setups, but I need to do some tests to confirm this.

**Comment by talregev** [comment]
It my analysis with google search and see similar issues.
I guess the new protobuf using c++17 syntax but the abseil is compile with c++11.

**Comment by traversaro** [comment]
> I guess the new protobuf using c++17 syntax but the abseil is compile with c++11.

No, abseil is compiled with C++17, see https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/4075#issuecomment-1562294904 . I guess that you see similar errors in Google searches as the abseil ABI depends on the C++ standard version used in compilation, and hence if there is a mismatch, some abseil symbol can be missing in the actual compiled library, resulting in a "error LNK2019: unresolved external symbol". However, this is not the only reason a linker may not find a symbol: in this case I think that the linker does not find the abseil symbol simply because nobody is linking the abseil shared libraries.

**Comment by traversaro** [comment]
Note that even if we fix compilation with new protobuf, the Windows build would still fail due to https://github.com/conda-forge/libignition-msgs1-feedstock/issues/30 (that is the reason why there is a failure now only on Windows). So we need to wait also for https://github.com/conda-forge/libignition-msgs1-feedstock/pull/83 to merged, or in the meanwhile we can pin manually libprotobuf to 3.21 .

**Comment by talregev** [comment]
> Note that even if we fix compilation with new protobuf, the Windows build would still fail due to [conda-forge/libignition-msgs1-feedstock#30](https://github.com/conda-forge/libignition-msgs1-feedstock/issues/30) (that is the reason why there is a failure now only on Windows). So we need to wait also for [conda-forge/libignition-msgs1-feedstock#83](https://github.com/conda-forge/libignition-msgs1-feedstock/pull/83) to merged, or in the meanwhile we can pin manually libprotobuf to 3.21 .

Can you pin manually libprotobuf to 3.21?
I can close this PR.

I also send you a respond email regards your email you sending me about my other PRs.
Are you still wish to talk with me?

**Comment by traversaro** [comment]
> > Note that even if we fix compilation with new protobuf, the Windows build would still fail due to [conda-forge/libignition-msgs1-feedstock#30](https://github.com/conda-forge/libignition-msgs1-feedstock/issues/30) (that is the reason why there is a failure now only on Windows). So we need to wait also for [conda-forge/libignition-msgs1-feedstock#83](https://github.com/conda-forge/libignition-msgs1-feedstock/pull/83) to merged, or in the meanwhile we can pin manually libprotobuf to 3.21 .
> 
> Can you pin manually libprotobuf to 3.21?

I hope to fix https://github.com/conda-forge/libignition-msgs1-feedstock/pull/83 soonish (1/2 days) and then fix Gazebo Classic compatibility with protobuf 4.23.2, so pinning should not be necessary.

> I also send you a respond email regards your email you sending me about my other PRs.
Are you still wish to talk with me?

Sure! Unfortunatly there have been some unplanned activities that took my time, I will contact you!

**Comment by talregev** [comment]
> I hope to fix [conda-forge/libignition-msgs1-feedstock#83](https://github.com/conda-forge/libignition-msgs1-feedstock/pull/83) soonish (1/2 days) and then fix Gazebo Classic compatibility with protobuf 4.23.2, so pinning should not be necessary.

Thank you for your quick respond. I am closing this PR.

**Comment by talregev** [comment]
@traversaro Why you close this PR?
https://github.com/conda-forge/libignition-msgs1-feedstock/pull/83

**Comment by traversaro** [comment]
> @traversaro Why you close this PR? [conda-forge/libignition-msgs1-feedstock#83](https://github.com/conda-forge/libignition-msgs1-feedstock/pull/83)

It was superseded by https://github.com/conda-forge/libignition-msgs1-feedstock/pull/86 , see https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4502 for the context.

**Comment by traversaro** [comment]
> > I hope to fix [conda-forge/libignition-msgs1-feedstock#83](https://github.com/conda-forge/libignition-msgs1-feedstock/pull/83) soonish (1/2 days) and then fix Gazebo Classic compatibility with protobuf 4.23.2, so pinning should not be necessary.
> 
> Thank you for your quick respond. I am closing this PR.

Unfortunatly this turned out to be more complicated then expected, as it also required several changes deep down in google's stack (protobuf&abseil):
* https://github.com/abseil/abseil-cpp/pull/1466
* https://github.com/protocolbuffers/protobuf/pull/12978

Anyhow, we should be converging soonish.

**Pull request closed without merging**
