### PR TITLE
[gazebo7] Update BitBucket links

### PR DESCRIPTION
**Pull request by chapulina**
Signed-off-by: Louise Poubel <louise@openrobotics.org>

### CODE REVIEW

**Comment by chapulina** [comment]
@osrf-jenkins run tests

**Comment by j-rivero** [comment]
@osrf-jenkins run tests

**Comment by chapulina** [comment]
@osrf-jenkins run tests

**Review by j-rivero — APPROVED** [review]
Approve after checked the gazebo11 PR. Assume changes are mostly the same.

**Pull request merged**
