### PR TITLE
Add support for cross-compilation in Gazebo

### PR DESCRIPTION
**Pull request by traversaro**
PR for gazebo similar to https://github.com/ignitionrobotics/ign-msgs/pull/60 . ~Currently WIP as now it is still under testing in https://github.com/conda-forge/gazebo-feedstock/pull/123 .~ The PR options have been validated in https://github.com/conda-forge/gazebo-feedstock/pull/123 .

### CODE REVIEW

**Comment by traversaro** [comment]
The PR is ready for review.

**Comment by traversaro** [comment]
fyi @Ace314159 if you ever want to enable cross-compilation of gazebo in vcpkg

**Comment by traversaro** [comment]
Hello everyone! If there is anything I can do to simply the merging of this PR, feel free to let me know, thanks!

**Comment by j-rivero** [comment]
@osrf-jenkins run tests

**Review by j-rivero — APPROVED** [review]
The ABI problems reported are not related to the changes in this PR, probably an outdated branch with respect to `gazebo11`. Good to go IMHO.

**Pull request merged**
