### PR TITLE
Rename io.h to avoid problems with Windows (gazebo11)

### PR DESCRIPTION
**Pull request by j-rivero**
The Windows failure in Gazebo11 seems to happen because we are introducing an internal io.h file inside the compilation and Windows is unable to get its own header with the same name. I don't think we are exporting the header or using it in any other place than the internal ode fork so I'm changing its name here.

### CODE REVIEW

**Comment by j-rivero** [comment]
@osrf-jenkins run tests

**Comment by j-rivero** [comment]
@osrf-jenkins run tests please

**Comment by j-rivero** [comment]
@osrf-jenkins run tests please

**Comment by j-rivero** [comment]
I've fixed some problems with Windows setup, running now [Build Status](https://build.osrfoundation.org/job/gazebo-ci-pr_any-windows7-amd64/2773/)

Rest of testing failures in other platforms seems unrelated to me.

**Review by nuclearsandwich — APPROVED** [review]

**Pull request merged**
