### PR TITLE
Ensure relocatable package config files

### LINKED ISSUE #2755: Gazebo does not have relocatable CMake configuration files
See https://cmake.org/cmake/help/v3.15/manual/cmake-packages.7.html#creating-relocatable-packages for a definition of relocatable CMake configuration files. In a nutshell, it means that you can move the installation directory of Gazebo after Gazebo has been installed, and Gazebo and consuming Gazebo libraries from CMake continue to work correctly. 

This is a known issue that I do not know if it feasible/it make sense to address for Gazebo Classic. However, I think it make sense to have a reference issue for this, so that we have an issue to refer to when implementing workarounds for this problems.

### LINKED ISSUE #2782: User dependent gazebo installation
Hey there,

I want to provide Gazebo via the conan package manager to some colleagues. Building all the components worked like a charm using conan's cmake build helpers and git tool. Also gazebo starts without problems for my user and I can compile plugins against the Gazebo C++ API using cmake.

However, if I upload the built package to our Artifactory server, and another user installs the pre-built binaries, Gazebo doesn't start and `find_package` cannot find Gazebo anymore.

We were able to start Gazebo under the other user by providing the environment variable `GAZEBO_RESOURCE_PATH` (see https://github.com/PX4/avoidance/issues/177).

But in general it seems that user-specific paths are compiled into the generated packages, both in cmake config files and so-files.
Is this the case? And if so, can Gazebo and its dependencies be compiled in a user-independent manner?

I could not find cmake options in any of the packages. I also didn't find any pointers in the documentation or READMEs.

Cheers,
Stefan

### PR DESCRIPTION
**Pull request by Pro**
The CMake config used absolute paths which doesn't allow to move the installed cmake files. This is the case, e.g., if you create a conan package and distribute the binaries to other users.

Fixes: https://github.com/osrf/gazebo/issues/2755
Fixes: https://github.com/osrf/gazebo/issues/2782

### CODE REVIEW

**Comment by traversaro** [comment]
FYI I think that some generated files may still not be relocatable (for example the `setup.sh` and `setup.bat` files), but depending on your use-case you may be not interested in those. If you are interested in those, I have some relocatable variants that I never pushed upstream until now: 
* https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/blob/master/scripts/setup-gazebo.sh
* https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/blob/master/scripts/setup-gazebo.bat

**Comment by scpeters** [comment]
I think I broke something because the tests that compile example code are failing

* https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-nvidia/553/testReport/junit/(root)/Plugins_ExamplesBuild_Plugins/Plugins_0/
* https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/2311/testReport/junit/(root)/Plugins_ExamplesBuild_Plugins/Plugins_0/

**Comment by scpeters** [comment]
> I think I broke something because the tests that compile example code are failing
> 
> * https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-nvidia/553/testReport/junit/(root)/Plugins_ExamplesBuild_Plugins/Plugins_0/
> * https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/2311/testReport/junit/(root)/Plugins_ExamplesBuild_Plugins/Plugins_0/

I had trouble reproducing this because I was running the tests directly instead of calling `ctest -R test_name`, which triggers the use of environment variables specified in [GazeboTestUtils.cmake](https://github.com/osrf/gazebo/blob/gazebo11_11.3.0/cmake/GazeboTestUtils.cmake#L70-L74), including `PKG_CONFIG_PATH` and `CMAKE_PREFIX_PATH`. The intention of setting those variables there is to help tests pass without running `make install` (7283291b8dc404410363033c90caae5b4cbc976a), but the `-I` paths are now broken. A different approach is taken to test compilation of example code without running `make install` by using a `FAKE_INSTALL` with `ExternalProject_Add`, but that may be prohibitive for a project as large as gazebo:

* https://github.com/ignitionrobotics/ign-cmake/blob/ignition-cmake2_2.6.2/CMakeLists.txt#L170-L181
* https://github.com/ignitionrobotics/ign-math/blob/ignition-math6_6.7.0/test/CMakeLists.txt#L31-L42

**Comment by scpeters** [comment]
reverting some environment variables in GazeboTestUtils in e7fcb46 fixes the compilation tests, though they now require `make install`. I think that's a reasonable trade-off unless someone wants to implement a `FAKE_INSTALL` target for testing

**Comment by scpeters** [comment]
this looks good to me now, but I'd like @j-rivero to take a look since I've modified it from the original version

**Review by j-rivero — APPROVED** [review]
The generated `.pc` files looks good to me. The failing tests in Windows are not related to these changes.

**Pull request merged**
