### PR TITLE
7 ➡️ 9

### PR DESCRIPTION
**Pull request by chapulina**
Merge `gazebo7` forward to `gazebo9`. Nothing major, mainly just one PR.

Includes #2800

### CODE REVIEW

**Comment by ahcorde** [comment]
@osrf-jenkins run tests please

**Comment by chapulina** [comment]
@osrf-jenkins run tests please

**Comment by scpeters** [comment]
this seems to revert https://github.com/osrf/gazebo/commit/98a5eb760ec564cefc43a628fc3352d5fe29a9d9 from a few years ago

**Comment by scpeters** [comment]
> this seems to revert [98a5eb7](https://github.com/osrf/gazebo/commit/98a5eb760ec564cefc43a628fc3352d5fe29a9d9) from a few years ago

which was part of osrf/gazebo PR 2572:

* https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/pull-requests/2572/page/1

**Comment by scpeters** [comment]
> > this seems to revert [98a5eb7](https://github.com/osrf/gazebo/commit/98a5eb760ec564cefc43a628fc3352d5fe29a9d9) from a few years ago
> 
> which was part of osrf/gazebo PR 2572:
> 
> * https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/pull-requests/2572/page/1

cc @iche033

**Comment by chapulina** [comment]
> this seems to revert 98a5eb7 from a few years ago

This is a forward-port of [PR 3195](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/pull-requests/3195/page/1) fixing https://github.com/osrf/gazebo/issues/2692 on Gazebo 7. That essentially added the `static_cast<uint64_t>` for Linux and macOS. Since this PR is basically just changing Windows, which was untested on Gazebo 7, I reverted it: bf171c4

**Comment by chapulina** [comment]
This PR is now just fixing a typo and some changelog entries, no code changes.

**Review by mabelzhang — APPROVED** [review]

**Pull request merged**
