### PR TITLE
Custom shadow caster materials

### PR DESCRIPTION
**Pull request by WilliamLewww**
I added a new SDF parameter <ignition:shadow_caster_material_name> to specify what shadow caster material should be used to render shadows.
```
<scene>
  <ignition:shadow_caster_material_name>Gazebo/shadow_caster_ignore_heightmap</ignition:shadow_caster_material_name>
  <background>0.0 0.0 0.0 1</background>
</scene>
```
Currently, the scene is hard-coded to always use "Gazebo/shadow_caster" for all shadow caster materials.

Adding custom shadow casters could also allow the usage of custom uniform parameters without clumping up "Gazebo/shadow_caster".

Related pull request: https://github.com/WilliamLewww/gazebo/pull/5

### CODE REVIEW

**Review by scpeters — COMMENTED** [review]
I managed to remove the input parameter to the service in https://github.com/scpeters/gazebo/commit/18092a276a029924069f667f558a9e1c9853efaf; please consider merging it in

**Comment by WilliamLewww** [comment]
The changes work great! I just merged in your branch.

**Comment by scpeters** [comment]
the CustomShadowCaster tests are failing on macOS:

* https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/2493/testReport/junit/(root)/CustomShadowCasterTest/DefaultShadowCaster/
* https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/2493/testReport/junit/(root)/CustomShadowCasterTest/CustomShadowCaster/

I think it's ok to disable these tests if there is not an easy fix

**Comment by WilliamLewww** [comment]
> the CustomShadowCaster tests are failing on macOS:
> 
>     * https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/2493/testReport/junit/(root)/CustomShadowCasterTest/DefaultShadowCaster/
> 
>     * https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/2493/testReport/junit/(root)/CustomShadowCasterTest/CustomShadowCaster/
> 
> 
> I think it's ok to disable these tests if there is not an easy fix

These tests I created use approximating for validation and can be unpredictable.
I think the build not failing is a good test, but I'll fix up the tests for completion :)

**Comment by WilliamLewww** [comment]
The test is still failing and I'll try to update it again before I just remove it.

**Comment by scpeters** [comment]
I did notice an issue with PCF on macOS in https://github.com/osrf/gazebo/pull/3036#pullrequestreview-710475916, but I'm not sure if that's related

**Comment by WilliamLewww** [comment]
#3036 uses separate shaders so that might not be the issue. I removed the integration test to prevent future error output.

**Comment by scpeters** [comment]
> #3036 uses separate shaders so that might not be the issue. I removed the integration test to prevent future error output.

the test is working on Ubuntu, so I would add it back in but disable it for macOS. For example, here is some cmake logic that skip tests depending on the operating system:

* https://github.com/osrf/gazebo/blob/10969364534f525788001c5409497e5e412af87b/test/integration/CMakeLists.txt#L126-L131
* https://github.com/osrf/gazebo/blob/10969364534f525788001c5409497e5e412af87b/test/performance/CMakeLists.txt#L21

**Review by scpeters — APPROVED** [review]

**Comment by Tobias-Fischer** [comment]
Hi @WilliamLewww @scpeters,

We received a bug report in the conda-forge repo (https://github.com/conda-forge/gazebo-feedstock/issues/90) that Gazebo 11.8 (where this PR first appears) does not start in Windows, with this error:

```
[Err] [..\gazebo\gui\main.cc:37] Ogre Error:ItemIdentityException: Resource with the name shadow_caster_vp_glsl already exists. in ResourceManager::add at ..\OgreMain\src\OgreResourceManager.cpp (line 158)
[Err] [..\gazebo\server_main.cc:57] Ogre Error:ItemIdentityException: Resource with the name shadow_caster_vp_glsl already exists. in ResourceManager::add at ..\OgreMain\src\OgreResourceManager.cpp (line 158)
[Err] [..\gazebo\transport\Connection.cc:273] The I/O operation has been aborted because of either a thread exit or an application requestValue[995]
```

I think that this PR is the culprit. Do you have any idea how to fix the issue? I am not sure whether the problem occurs outside of our conda-forge build.

/cc @johnwason @wolfv @traversaro @seanyen

**Comment by WilliamLewww** [comment]
> Hi @WilliamLewww @scpeters,
> 
> We received a bug report in the conda-forge repo ([conda-forge/gazebo-feedstock#90](https://github.com/conda-forge/gazebo-feedstock/issues/90)) that Gazebo 11.8 (where this PR first appears) does not start in Windows, with this error:
> 
> ```
> [Err] [..\gazebo\gui\main.cc:37] Ogre Error:ItemIdentityException: Resource with the name shadow_caster_vp_glsl already exists. in ResourceManager::add at ..\OgreMain\src\OgreResourceManager.cpp (line 158)
> [Err] [..\gazebo\server_main.cc:57] Ogre Error:ItemIdentityException: Resource with the name shadow_caster_vp_glsl already exists. in ResourceManager::add at ..\OgreMain\src\OgreResourceManager.cpp (line 158)
> [Err] [..\gazebo\transport\Connection.cc:273] The I/O operation has been aborted because of either a thread exit or an application requestValue[995]
> ```
> 
> I think that this PR is the culprit. Do you have any idea how to fix the issue? I am not sure whether the problem occurs outside of our conda-forge build.
> 
> /cc @johnwason @wolfv @traversaro @seanyen

I think I see the issue where **shadow_caster_vp_glsl** is defined both in:
- gazebo/media/materials/scripts/shadow_caster.program
- gazebo/media/materials/scripts/shadow_caster_ignore_heightmap.program

A temporary fix could be to:
1. Delete the following lines
https://github.com/osrf/gazebo/blob/b502f17729302fa0da8e2a00ffbd69112bb7e6aa/media/materials/scripts/shadow_caster_ignore_heightmap.program#L1-L10

**If that doesn't work then**
2. Change
https://github.com/osrf/gazebo/blob/b502f17729302fa0da8e2a00ffbd69112bb7e6aa/media/materials/scripts/shadow_caster_ignore_heightmap.program#L32
to **vertex_program_ref DeferredShading/vs**

I'm currently checking out the issue and rebuilding my workspace, but I'll send a follow up if the solution works on my end.

**Comment by Tobias-Fischer** [comment]
Thanks for looking into it so quickly @WilliamLewww. It would be great if you let us know which of your two suggestions ends up being the better one, and we can patch it on conda-forge until a new release comes out.

**Comment by WilliamLewww** [comment]
> Thanks for looking into it so quickly @WilliamLewww. It would be great if you let us know which of your two suggestions ends up being the better one, and we can patch it on conda-forge until a new release comes out.

No worries! I was able to fix the issue on my end with the following changes: https://github.com/WilliamLewww/gazebo/commit/8d5043439da5ee5fe7b8912aa7bb8dc33f16a066.

I will be opening a pull request soon to add the changes. Let me know if this fixes the issue you ran into.

**Pull request merged**
