### PR TITLE
Prepare 11.15.0 release

### PR DESCRIPTION
**Pull request by j-rivero**
# 🎈 Release

Preparation for 11.15.0

Comparison to 11.14.0: https://github.com/gazebosim/gazebo-classic/compare/gazebo11_11.14.0...gazebo11

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by scpeters — APPROVED** [review]

**Review by traversaro — APPROVED** [review]

**Comment by talregev** [comment]
@traversaro Are you going to release?

**Comment by scpeters** [comment]
I think we'll need up to update the changelog with the recent pull requests that have been merged since this was opened on Feb 14

**Comment by traversaro** [comment]
@scpeters @j-rivero Can I update the changelog as mentioned in https://github.com/gazebosim/gazebo-classic/pull/3369#issuecomment-2148548770 or there is something else that needs to be done? Thanks!

**Comment by scpeters** [comment]
> @scpeters @j-rivero Can I update the changelog as mentioned in [#3369 (comment)](https://github.com/gazebosim/gazebo-classic/pull/3369#issuecomment-2148548770) or there is something else that needs to be done? Thanks!

Yes please! Go for it

**Comment by azeey** [comment]
I've updated the Changelog.

**Review by scpeters — APPROVED** [review]

**Pull request merged**
