### PR TITLE
[backport Gazebo7] Fixed crash when collision size is zero

### PR DESCRIPTION
**Pull request by ahcorde**
Orignal PR https://github.com/osrf/gazebo/pull/2768

Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Comment by mabelzhang** [comment]
I tested this on Ubuntu 16.04, since that's where Kinetic + Gazebo 7 is official.
I'm getting the same compiler error as Jenkins - isnan not declared in this scope. Changing to `std::isnan` worked. The next error I'm getting is line 803: `'Name' was not declared in this scope`.

**Comment by mabelzhang** [comment]
I retested and it works. Specifying `--verbose` shows the error printout. (In non-verbose mode, only the sdformat error message is printed, `Error [Param.cc:452] Unable to set value [-nan -nan -nan] for key[size]`.)

Linux CI looks okay.

@j-rivero @scpeters Mac is saying pip3 not found?
```
++ pip3 install lxml
./scripts/jenkins-scripts/lib/project-default-devel-homebrew-amd64.bash: line 81: pip3: command not found
Build step 'Execute shell' marked build as failure
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: Test reports were found but none of them are new. Did leafNodes run? 
For example, /Users/jenkins/workspace/gazebo-ci-pr_any-homebrew-amd64/build/test_results/EXAMPLE_examples_build.xml is 1 day 15 hr old
```

and Windows is not finding Qt:
```
CMake Error at C:/Program Files/CMake/share/cmake-3.15/Modules/FindQt4.cmake:1314 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
```

None of this is related to this PR, but I don't know if I should approve and merge if some of the CIs hadn't run...

**Comment by scpeters** [comment]
> Mac is saying pip3 not found?

I think that was an intermittent failure that should be resolved now by https://github.com/ignition-tooling/release-tools/pull/236

**Comment by scpeters** [comment]
@osrf-jenkins run tests please

**Comment by mabelzhang** [comment]
Thanks Steve! Looks like Mac has a bunch of complaints about cmath and math.h, e.g.
```
In file included from /Users/jenkins/workspace/gazebo-ci-pr_any-homebrew-amd64/gazebo/gazebo/common/Animation.cc:19:
In file included from /usr/local/Cellar/ignition-math2/2.9.0/include/ignition/math2/ignition/math/Spline.hh:22:
In file included from /usr/local/Cellar/ignition-math2/2.9.0/include/ignition/math2/ignition/math/Helpers.hh:20:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:318:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
```
Same thing for isfinite, isinf, isnan, isnormal, isgreater, etc. That looks like it shouldn't happen?

**Comment by ahcorde** [comment]
@mabelzhang [CI is passing](https://build.osrfoundation.org/job/gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-nvidia/265/consoleFull#45593342ed30c675-ba23-4c35-b655-f5c948f97581)

```
131: [ RUN      ] Visual_TEST.CollisionZero
131: [Msg] Waiting for master.
131: [Msg] Connected to gazebo master @ http://127.0.0.1:11345
131: [Msg] Publicized address: 172.17.0.2
131: [Dbg] [ServerFixture.cc:207] ServerFixture load in 0.8 seconds, timeout after 600 seconds
131: Error [Param.cc:452] Unable to set value [-nan -nan -nan] for key[size]
131: [Err] [Visual.cc:805] box::link::collision__COLLISION_VISUAL__: Size of the collision contains one or several zeros. Collisions may not visualize properly.
131: [Err] [Visual.cc:805] sphere::link::collision__COLLISION_VISUAL__: Size of the collision contains one or several zeros. Collisions may not visualize properly.
131: [Err] [Visual.cc:805] cylinder::link::collision__COLLISION_VISUAL__: Size of the collision contains one or several zeros. Collisions may not visualize properly.
131: [Dbg] [ServerFixture.cc:133] ServerFixture::Unload
131: [       OK ] Visual_TEST.CollisionZero (3049 ms)
```

**Review by mabelzhang — APPROVED** [review]
Verified locally - test failed before the fix, and passed after the fix in Ubuntu 16 + Gazebo 7.

**Pull request merged**
