### PR TITLE
[CI][vcpkg][Windows] Build gazebo for windows with cmake vcpkg

### PR DESCRIPTION
**Pull request by talregev**
Build gazebo for windows with cmake vcpkg.
To find all dependencies need to change cmake that it will compile both with native and vcpkg build.
I will do it in next PR, and I will need community help.

All dependencies are cache, and It much faster configure when it take it from the cache folder.

@traversaro
@chapulina

### CODE REVIEW

**Comment by talregev** [comment]
@traversaro from our conversion here:
https://github.com/microsoft/vcpkg/pull/31280
Can I do anything to help getting this PR?

**Comment by traversaro** [comment]
@talregev Thanks for the contribution. The `deps/vcpkg/manifests/windows/vcpkg.json` is only useful for CI (in that case, we could also thinking of having this CI in a different repo), or it is useful to have it in the main repo for some reason?

**Comment by talregev** [comment]
> @talregev Thanks for the contribution. The `deps/vcpkg/manifests/windows/vcpkg.json` is only useful for CI (in that case, we could also thinking of having this CI in a different repo), or it is useful to have it in the main repo for some reason?

It useful for any case that other want to build gazebo in windows.
You can build gazebo without the ci (with the commands from the ci). 
This PR give you a way how to compile gazebo on your windows pc without install anything.  (except git)

**Comment by talregev** [comment]
@traversaro you cannot build gazebo with vcpkg alone (with it own gazebo vcpkg.json file). It break. I made a PR for that.
You can read and have a comments there if you want:
https://github.com/microsoft/vcpkg/pull/30424

Currently to build gazebo on windows without anaconda and with vcpkg, it with this PR. 
So this file: `deps/vcpkg/manifests/windows/vcpkg.json` is part from the build.

**Comment by traversaro** [comment]
And the resulting Gazebo is then working or not? I just noticed https://github.com/gazebosim/gazebo-classic/pull/3320 , and from there it seems that the resulting gazebo is not starting.

**Comment by talregev** [comment]
> And the resulting Gazebo is then working or not? I just noticed #3320 , and from there it seems that the resulting gazebo is not starting.

The same here. But I think it not concerning the compilation. I think I am doing something wrong. 
I know I compile gazebo correctly and with help of the community I will able to run it.

**Comment by traversaro** [comment]
> The same here. But I think it not concerning the compilation. I think I am doing something wrong.
> I know I compile gazebo correctly and with help of the community I will able to run it.

Thanks! So perhaps it could make sense to have something running before merging this PR? In the meanwhile, you could host the `vcpkg.json` metadata in a separate repository, so people that want to test can easily do that (by specifying the location of the `vcpkg.json` via `VCPKG_MANIFEST_DIR`).

**Comment by talregev** [comment]
> Thanks! So perhaps it could make sense to have something running before merging this PR?

I know the compilation is correct. Do you think we need to do something else in compilation? 
If compilation is correct, and can verify with you, we can merge this PR.

Do you have windows machine to test it out too? 

>  In the meanwhile, you could host the vcpkg.json metadata in a separate repository

Why you want to host the `vcpkg.json` in a separate repository? It part of the build. It tell which packages to install. 
It the same you have a `CMakeLists.txt﻿` and inside all the find packages for all your 3rdparties. 

If you want other will test it easily too, then leave the `vcpkg.json` on this repo. There is no meaning for this build, or this PR when we put this in other place.

**Comment by talregev** [comment]
@traversaro This is outdated version. I switch to other PR I did:
x64 + x86
https://github.com/gazebosim/gazebo-classic/pull/3320

**Pull request closed without merging**
